project:
  type: website

website:
  title: "website für Git Workshop Repo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: pictures.qmd
        text: Pictures

format:
  html:
    theme:
      - cosmo
      - brand
    css: css/styles.css
    toc: true



